### ISSUE TITLE
ミッション途中のaddGroup()やdestroy()に非対応

### ISSUE THREAD

**Issue by Maigo-2-1** [Tama010/DCS_SAM-Script#2]
ミッション開始時に存在している又はLATE ACTIVATIONのGroupやUnitはinitObjList()で認識されます。
しかしながら、ミッション開始後にaddGroup()すると、認識されず、ARMが接近してもレーダーはオンです。
また、destroy()で全ユニットを消滅させた後addGroup()すると、getName()などの関数でエラーが発生します。

**Comment by Tama010** [comment]
掲載ありがとうございます。
確認・検証させて頂きます。

**Comment by Tama010** [comment]
Maigo-2-1様のソースをそのまま活用させて頂きました。
https://github.com/Tama010/DCS_SAM-Script/tree/Pre-release
こちらでテストした結果、問題は発見されず...
本当にありがとうございました。
