### ISSUE TITLE
judgeEwrHandle()が実行されない。

### ISSUE THREAD

**Issue by Maigo-2-1** [Tama010/DCS_SAM-Script#4]
対策済でしたら恐縮です。
194行目　if string.find(_unit:getName(), _ALWAYSACTIVATED) == false then
で、文字列が見つからなかったときの戻り値は nil であって false じゃないので、
195行目のjudgeEwrHandle()に到達せず、EWRが寝ていなかったようです。

**Comment by Maigo-2-1** [comment]
お忙しいところ恐縮です。よろしくお願いします！

**Comment by Tama010** [comment]
ver2.2で対応致しました。
https://github.com/Tama010/DCS_SAM-Script/tree/Pre-release
